config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView, name='index'),
    path('vehiculo/', include('vehiculo.urls')),
    path('', include('usuario.urls')),
]

usuario/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('registro/', views.UserRegistroView.as_view(), name='registro'),
]
 

vehiculo/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('list/', views.VehiculoView.as_view(), name='list_vehiculos'),
    path('add/', views.VehiculoCreateView.as_view(), name='create_vehiculos')
]
 

usuario/models.py
from django.db import models

# Create your models here.

vehiculo/models.py
from django.db import models


# Create your models here.

class Vehiculo(models.Model):
    MARCAS = [
        ('Fiat', 'Fiat'),
        ('Chevrolet', 'Chevrolet'),
        ('Ford', 'Ford'),
        ('Toyota', 'Toyota'),
    ]
    
    CATEGORIA_VEHICULO = [
        ('Particular', 'Vehículo Particular'),
        ('Transporte', 'Vehículo de Transporte'),
        ('Carga', 'Vehículo de Carga'),
    ]
    
    marca= models.CharField(max_length=20, blank=False, null=False, choices=MARCAS, default='Ford')
    modelo= models.CharField(max_length=100, blank=False, null=False)
    serial_carroceria= models.CharField(max_length=50, blank=False, null=False)
    serial_motor= models.CharField(max_length=50, blank=False, null=False)
    categoria= models.CharField(max_length=20, blank=False, null=False, choices=CATEGORIA_VEHICULO, default='Particular')
    precio = models.IntegerField(null=False, blank=False)
    fecha_creacion = models.DateField(auto_now_add=True)   #función auspiciada por Hugo
    fecha_modificacion = models.DateField(auto_now=True)   #función auspiciada por Hugo
    
    def filtrar_por_precios(self):
        if self.precio <= 10000:
            return 'Bajo'
        elif 10000 < self.precio <= 30000:
            return 'Medio'
        else:
            return 'Alto'
    
    class Meta:
        permissions = [
            ("visualizar_catalogo", "Puede ver el catálogo de vehículos"),
            ("add_vehiculomodel", "Puede Agregar Nuevos Vehiculos"),
        ]
    
    def __str__(self):
        return f"{self.marca} {self.modelo}"

config/views.py
from django.shortcuts import render

def IndexView (request):
    return render(request, 'index.html', {})

usuario/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib import messages


from django.contrib.auth.models import Permission

# VISTA BASADA EN CLASE PARA REGISTRO
class UserRegistroView(CreateView):
    form_class =  UserCreationForm
    template_name = 'usuarios/registro.html'
    success_url = reverse_lazy('login')
    
    def form_valid(self, form):
        
        response = super().form_valid(form)
        usuario = form.instance  #obtenemos la instancia de la Clase User
        permiso = Permission.objects.get(codename='visualizar_catalogo')
        permiso2 = Permission.objects.get(codename='add_vehiculomodel')#obtenemos permiso de la bd
        usuario.user_permissions.add(permiso, permiso2) #agregamos permiso al usuario
        usuario.save()
 
        
        
        messages.success(self.request, 'Registro realizo con éxito.')
        return response
    
    

# VISTA BASADA EN CLASE PARA LOGIN
class UserLoginView(LoginView):
    template_name = 'usuarios/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('index')

    
    def form_valid(self, form):
        messages.success(self.request, 'Login exitoso.')
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return self.get_redirect_url() or self.success_url
    
    
#vista de logout
class UserLogoutView(LogoutView):
    next_page = 'index'
    
    def dispatch(self, request, *args, **kwargs):
        messages.success(self.request, 'Ha cerrado la sesión exitosamente.')
        return super().dispatch(request, *args, **kwargs)
    

vehiculo/views.py
from django.http.response import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls   import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin 
from django.shortcuts import redirect
from django.contrib import messages

from .models import Vehiculo

# Create your views here.

class VehiculoView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Vehiculo
    template_name = "vehiculos/list_vehiculo.html"
    context_object_name = 'list_vehiculos'
   
    permission_required = 'vehiculos.view_vehiculo'
   
    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.error(self.request, "Usted no tiene permisos para acceder a la vista.")
            return redirect("login")
       
        else:
            messages.info(self.request, "Para continuar, por favor inicie sesión.")
            return redirect("login")



class VehiculoCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Vehiculo
    template_name = "vehiculos/create_vehiculo.html"
    fields = ['marca', 'modelo', 'serial_carroceria', 'serial_motor', 'categoria', 'precio']
    success_url = reverse_lazy('create_vehiculos')
    permission_required = 'add_vehiculomodel'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.error(self.request, "Usted no tiene permisos para acceder a la vista.")
            return redirect("login")
       
        else:
            messages.info(self.request, "Para continuar, por favor inicie sesión.")
            return redirect("login")

templates/index.html
{% extends "layouts/base.html" %}

{% block contenido %}
<main class="container py-5">
    <section>
        <h1 class="text-center py-3">Catálogo de vehículo</h1>
    </section>
</main>

{% endblock contenido %}

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<style>

</style>
</head>
<body>

    {% include "partials/navbar.html" %}

    {% block contenido %} {% endblock contenido %}




</body>
</html>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand">Vehículos</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "index" %}">Inicio</a>
          </li>
          {% if perms.vehiculo.add_vehiculomodel %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "create_vehiculos" %}">Agregar</a>
          </li>
          {% endif %}
          {% if perms.vehiculo.visualizar_catalogo %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "list_vehiculos" %}">Listar</a>
          <li>
              {% endif %}
        {% if not user.is_authenticated %}
        <div class="text-end">
          <a class="btn btn-primary" href="{% url "login" %}">Login</a>
          <a class="btn btn-warning" href="{% url "registro" %}">Sign-up</a>         
        </div>
        {% endif %}

        {% if user.is_authenticated %}
        <form method="post" action="{% url "logout" %}" class="ms-3">
            {% csrf_token %}
            <button type="input" class="btn btn-danger">Logout</button>
        </form>
        {% endif %}
        </li>

          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/usuarios/login.html
{% extends "layouts/base.html" %}


{% block contenido %}

<main class="container">
    <section>
        <h1 class="text-center py-5">Página de login de usuario</h1>
    </section>
    <section>
        <div class="row justify-content-center">
            <div class="col-12 col-md-5 col-lg-4">
                <form method="post">
                    {% csrf_token %}
                    {% load widget_tweaks %}

                    <div class="form-group">
                        <label for="id_username">Nombre de usuario:</label>
                        {{ form.username|add_class:"form-control" }}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Contraseña:</label>
                        {{ form.password|add_class:"form-control" }}
                    </div>
            
                    <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                </form>
            </div>
        </div>
    </section>
</main>

{% endblock contenido %}

templates/usuarios/registro.html
{% extends "layouts/base.html" %}


{% block contenido %}
<header>
    <h1>Página de registro de usuarios</h1>
</header>

<main class="container">
    <section>
        <form method="post">
            {% csrf_token %}
            {% load widget_tweaks %}
    
            <div class="form-group">
                <label for="id_username">Nombre de usuario:</label>
                <div class="col-md-6">
                    {{ form.username|add_class:"form-control" }}
                </div>
                <small class="form-text text-muted">Requerido. 150 caracteres como máximo. Únicamente letras, dígitos y @/./+/-/_</small>
            </div>
    
            <div class="form-group">
                <label for="id_password1">Contraseña:</label>
                <div class="col-md-6">
                    {{ form.password1|add_class:"form-control" }}
                </div>
                <small class="form-text text-muted">
                    <ul>
                        <li>Su contraseña no puede asemejarse tanto a su otra información personal.</li>
                        <li>Su contraseña debe contener al menos 8 caracteres.</li>
                        <li>Su contraseña no puede ser una clave utilizada comúnmente.</li>
                        <li>Su contraseña no puede ser completamente numérica.</li>
                    </ul>
                </small>
            </div>
    
            <div class="form-group">
                <label for="id_password2">Contraseña (confirmación):</label>
                <div class="col-md-6">
                    {{ form.password2|add_class:"form-control" }}
                </div>
                <small class="form-text text-muted">Para verificar, introduzca la misma contraseña anterior.</small>
            </div>
    
            <button type="submit" class="btn btn-primary">Crear usuario</button>
    
        </form>
    </section>
</main>

{% endblock contenido %}

templates/vehiculos/create_vehiculo.html
{% extends "layouts/base.html" %}

{% block contenido %}

    <main class="container">
        <section>
            <h1 class="text-center py-5">Registra un nuevo vehículo.</h1>
        </section>

        <section>

            <div class="row justify-content-center">
                <div class="col-12 col-md-5">
                    <form method="post">
                        {% csrf_token %}
                        {% load widget_tweaks %}

                        <div class="form-group">
                            <label for="id_marca">Marca:</label>
                            {{ form.marca|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_modelo">Modelo:</label>
                            {{ form.modelo|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_serial_carroceria">Serial Carrocería:</label>
                            {{ form.serial_carroceria|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_serial_motor">Serial Motor:</label>
                            {{ form.serial_motor|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_categoria">Categoría:</label>
                            {{ form.categoria|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            <label for="id_precio">Precio:</label>
                            {{ form.precio|add_class:"form-control" }}
                        </div>
                        <div>
                            <button class="btn btn-primary">Registrar vehículo</button>
                        </div>
                    </form>
                </div>
            </div>

        </section>

    </main>
{% endblock  %}

templates/vehiculos/list_vehiculo.html
{% extends "layouts/base.html" %}
{% block contenido %}
 
<header>
    <h1 class="text-center py-3">Catálogo de Vehículos</h1>
</header>
 
<main class="container py-3">
    <section>
 
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                  <th scope="col">Marca</th>
                  <th scope="col">Modelo</th>
                  <th scope="col">Serial Carrocería</th>
                  <th scope="col">Serial Motor</th>
                  <th scope="col">Categoría</th>
                  <th scope="col">Precio</th>
                  <th scope="col">Condición precio</th>
                </tr>
              </thead>
              <tbody>
                {% for vehiculo in list_vehiculos %}
                <tr>
                  <td>{{vehiculo.marca}}</td>
                  <td>{{vehiculo.modelo}}</td>
                  <td>{{vehiculo.serial_carroceria}}</td>
                  <td>{{vehiculo.serial_motor}}</td>
                  <td>{{vehiculo.categoria}}</td>
                  <td>$ {{vehiculo.precio}}</td>
                  <td>{{vehiculo.filtrar_por_precios}}</td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
 
    </section>
</main>
{% endblock contenido %}